#!/usr/bin/env bash

## Install ansible
sudo pacman -S ansible --noconfirm

# pull ansible
git clone https://github.com/coldb/ansible-omarchy.git
cd ansible-omarchy

if [ -n "$1" ]; then
  exec ./run "$1"
else
  optional_tags="install install-personal"

  selected_tags=$(echo "$optional_tags" | tr ' ' '\n' | sort -r | fzf --prompt="What tags to run: " --multi --header="Use tab to multi-select")

  if [ -n "$selected_tags" ]; then
    tag_list=$(echo "$selected_tags" | tr '\n' ',')
    tag_list=${tag_list%,}

    exec ./run "$tag_list"
  else
    echo "No tags selected"
  fi
fi
