#!/usr/bin/env bash

## Install ansible
sudo pacman -S ansible --noconfirm

# pull ansible
git clone https://github.com/coldb/ansible-omarchy.git
cd ansible-omarchy

if [ -n "$1" ]; then
  ansible-playbook ansible/local.yaml -t $1 --ask-become-pass --ask-vault-pass
else
  optional_tags="install install-personal install-work"

  selected_tags=$(echo "$optional_tags" | tr ' ' '\n' | sort -r | fzf --prompt="What tags to run: " --multi --header="Use tab to multi-select")

  if [ -n "$selected_tags" ]; then
    tag_list=$(echo "$selected_tags" | tr '\n' ',')
    tag_list=${tag_list%,}

    ansible-playbook ansible/local.yaml -t $tag_list --ask-become-pass --ask-vault-pass
  else
    echo "No tags selected"
  fi
fi
