- name: Terminal - Ghostty
  tags:
    - install
    - install-ghostty
    - update
    - update-ghostty

  block:
    - name: Stow ghostty dotfiles
      stow:
        folders: [ghostty]
        dotfiles_dir: "{{ dotfiles_dir }}"
        force: true

    - name: Install Ghostty package
      package:
        name: ghostty
        state: present
      become: true

    - name: Set Ghostty as the default terminal
      command: omarchy default terminal ghostty
      changed_when: true
