- block:
  - name: Stow ghostty dotfiles
    stow:
      folders: [ghostty]
      dotfiles_dir: "{{ dotfiles_dir }}"
      force: true

  tags:
    - install
    - install-ghostty
    - update
    - update-ghostty
