- name: Applications - Browsers - Firefox
  tags:
    - install
    - install-browsers
    - install-firefox
    - update
    - update-browsers
    - update-firefox

  block:
    - name: Install firefox
      become: true
      package:
        name: firefox
