- block:
  - name: Install firefox
    become: true
    package:
      name: firefox

  tags:
    - install
    - install-browsers
    - install-firefox
    - update
    - update-browsers
    - update-firefox
