- name: Applications - AI - Cursor
  tags:
    - install
    - install-ai
    - install-cursor
    - update
    - update-ai
    - update-cursor

  block:
    - name: Install Cursor
      become: true
      package:
        name: cursor-bin
