- name: Setup SSH
  tags:
    - install
    - install-ssh
    - update
    - update-ssh

  block:
    - name: Set SSH key facts
      set_fact:
        key_files:
          - source: "{{ dotfiles_dir }}/.ssh/id_ed25519_gh"
            target: "{{ home_dir }}/.ssh/id_ed25519_gh"

    - name: Ensure .ssh directory exists
      file:
        dest: "{{ item.target | dirname }}"
        mode: "0700"
        state: directory
      loop: "{{ key_files }}"

    - name: Add GitHub host key to known_hosts
      known_hosts:
        path: "{{ home_dir }}/.ssh/known_hosts"
        name: github.com
        key: "{{ lookup('pipe', 'ssh-keyscan -H github.com 2>/dev/null') }}"

    - name: Install SSH private key
      copy:
        src: "{{ item.source }}"
        dest: "{{ item.target }}"
        mode: "0600"
      loop: "{{ key_files }}"

    - name: Install SSH public key
      copy:
        src: "{{ item.source }}.pub"
        dest: "{{ item.target }}.pub"
        mode: "0644"
      loop: "{{ key_files }}"

    - name: Ensure custom GitHub SSH config is present
      ansible.builtin.blockinfile:
        path: "{{ home_dir }}/.ssh/config"
        block: |
          Host github.com
            HostName github.com
            User git
            IdentityFile ~/.ssh/id_ed25519_gh
            IdentitiesOnly yes
        append_newline: true
        prepend_newline: true
        create: true
        mode: "0600"
        marker: "# {mark} ANSIBLE MANAGED GITHUB CONFIG"

    - name: Read ansible-omarchy origin remote
      ansible.builtin.command:
        argv:
          - git
          - remote
          - get-url
          - origin
      args:
        chdir: "{{ (playbook_dir ~ '/..') | realpath }}"
      register: ansible_omarchy_origin_remote
      changed_when: false

    - name: Switch ansible-omarchy origin remote to SSH
      ansible.builtin.command:
        argv:
          - git
          - remote
          - set-url
          - origin
          - git@github.com:coldb/ansible-omarchy.git
      args:
        chdir: "{{ (playbook_dir ~ '/..') | realpath }}"
      when: ansible_omarchy_origin_remote.stdout == 'https://github.com/coldb/ansible-omarchy.git'
