- block:
  - name: Stow hyprland dotfiles
    stow:
      folders: [hypr]
      dotfiles_dir: "{{ dotfiles_dir }}"
      force: true

  - name: Reload hyprland config
    command: hyprctl reload

  tags:
    - install
    - install-hyprland
    - update
    - update-hyprland
