- block:
  - name: Install k9s
    become: true
    package:
      name: k9s

  tags:
    - install
    - install-development
    - install-k8s-tools
    - install-k9s
    - update
    - update-development
    - update-k8s-tools
    - update-k9s
