- name: Applications - KubeCtl
  tags:
    - install
    - install-development
    - install-k8s-tools
    - install-kubectl
    - update
    - update-development
    - update-k8s-tools
    - update-kubectl

  block:
    - name: Install kubectl
      become: true
      package:
        name: kubectl
