- name: Application - mise
  tags:
    - install
    - install-development
    - install-mise
    - update
    - update-development
    - update-mise

  block:
    - name: Install mise
      become: true
      package:
        name: mise

    - name: Stow mise dotfiles
      stow:
        folders: [mise]
        dotfiles_dir: "{{ dotfiles_dir }}"
        force: true

    - name: Install mise tools from config
      command: mise install
      changed_when: false
