- name: Applications - Neovim
  tags:
    - install
    - install-development
    - install-neovim
    - update
    - update-development
    - update-neovim

  block:
    - name: Install neovim
      become: true
      package:
        name: neovim

    - name: Stow neovim dotfiles
      stow:
        folders: [neovim]
        dotfiles_dir: "{{ dotfiles_dir }}"
