- block:
  - name: Install pgcli
    become: true
    package:
      name: pgcli

  tags:
    - install
    - install-development
    - install-pgcli
    - update
    - update-development
    - update-pgcli
