- name: Applications - Thunderbird
  tags:
    - install
    - install-thunderbird
    - update
    - update-thunderbird

  block:
    - name: Install thunderbird
      become: true
      package:
        name: thunderbird
