- name: Applications - tmux
  tags:
    - install
    - install-tmux
    - update
    - update-tmux

  block:
    - name: Install tmux
      become: true
      package:
        name:
          - tmux
          - bash-completion

    - name: Install tmux tpack-bin
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        name: tpack-bin
        state: present
        use: yay

    - name: Stow tmux dotfiles
      stow:
        folders: [tmux]
        dotfiles_dir: "{{ dotfiles_dir }}"
        force: true
