- hosts: localhost
  connection: local

  tasks:
    - import_tasks: tasks/setup.yaml
    - import_tasks: tasks/applications/_index.yaml
    - import_tasks: tasks/ssh.yaml
    - import_tasks: tasks/shell/_index.yaml
