- hosts: localhost
  connection: local

  tasks:
    - name: Setup
      import_tasks: tasks/setup.yaml
    - name: Setup dotfiles
      import_tasks: tasks/setup-scripts.yaml
    - name: Applications
      import_tasks: tasks/applications/_index.yaml
    - name: Tools
      import_tasks: tasks/tools.yaml
    - name: SSH
      import_tasks: tasks/ssh.yaml
    - name: Desktop
      import_tasks: tasks/desktop/_index.yaml
    - name: Shell
      import_tasks: tasks/shell/_index.yaml
    - name: Terminal
      import_tasks: tasks/terminal/_index.yaml
    - name: Personal Development Environment
      import_tasks: tasks/personal.yaml
